Repository DOSOPT-CDS-TABLING/Tabling-Android, pull requests merged in 2023-11, with the labels that each got.

#2 [init] 프로젝트 기초 세팅
  .editorconfig
  .github/workflows/pr_builder.yml
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/org/sopt/tabling/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/tabling/data/datasource/remote/DummyDataSource.kt
  app/src/main/java/org/sopt/tabling/data/model/request/RequestDummyDto.kt
  app/src/main/java/org/sopt/tabling/data/model/response/ResponseDummyDto.kt
  app/src/main/java/org/sopt/tabling/data/repository/DummyRepositoryImpl.kt
  app/src/main/java/org/sopt/tabling/data/service/DummyService.kt
  app/src/main/java/org/sopt/tabling/domain/model/DummyData.kt
  app/src/main/java/org/sopt/tabling/domain/repository/DummyRepository.kt
  app/src/main/java/org/sopt/tabling/presentation/common/ViewModelFactory.kt
  app/src/main/java/org/sopt/tabling/presentation/dummy/DummyActivity.kt
  app/src/main/java/org/sopt/tabling/presentation/dummy/DummyViewModel.kt
  app/src/main/java/org/sopt/tabling/util/ItemDiffCallback.kt
  app/src/main/java/org/sopt/tabling/util/UiState.kt
  app/src/main/java/org/sopt/tabling/util/binding/BindingActivity.kt
  app/src/main/java/org/sopt/tabling/util/binding/BindingFragment.kt
  app/src/main/java/org/sopt/tabling/util/extension/ContextExt.kt
  app/src/main/java/org/sopt/tabling/util/extension/IntentExt.kt
  app/src/main/java/org/sopt/tabling/util/extension/ViewExt.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/layout/activity_dummy.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearance.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/org/sopt/tabling/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: 🔅 init 🔅, 🐸 지현 🐸

#5 [feat] 지역 인기 매장 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/tabling/data/model/response/ResponsePopularStoreDto.kt
  app/src/main/java/org/sopt/tabling/presentation/store/PopularStoreActivity.kt
  app/src/main/java/org/sopt/tabling/presentation/store/PopularStoreAdapter.kt
  app/src/main/java/org/sopt/tabling/presentation/store/StoreViewModel.kt
  app/src/main/java/org/sopt/tabling/util/binding/BindingAdapter.kt
  app/src/main/res/color/selector_popular_store_chip_background.xml
  app/src/main/res/color/selector_popular_store_chip_stroke.xml
  app/src/main/res/color/selector_popular_store_chip_text.xml
  app/src/main/res/drawable/ic_arrow_down_black_36px.xml
  app/src/main/res/drawable/ic_back_gray_800_24px.xml
  app/src/main/res/drawable/ic_people_grey_100_24px.xml
  app/src/main/res/drawable/ic_polygon_gray_800_8px.xml
  app/src/main/res/drawable/ic_star_yellow_14px.xml
  app/src/main/res/drawable/shape_gradient_white_rect.xml
  app/src/main/res/layout/activity_popular_store.xml
  app/src/main/res/layout/item_popular_store.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 💫 feat 💫, ➡️ 민우 ➡️

#10 [init] 서버통신 기초세팅
  .github/workflows/pr_builder.yml
  app/build.gradle
  app/src/main/java/org/sopt/tabling/data/ApiFactory.kt
Labels: 🔅 init 🔅, 🐸 지현 🐸

#7 [feat] 대기 상세 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/tabling/data/model/response/ResponseWaitingDetailDto.kt
  app/src/main/java/org/sopt/tabling/presentation/waiting/WaitingDetailActivity.kt
  app/src/main/java/org/sopt/tabling/presentation/waiting/WaitingViewModel.kt
  app/src/main/res/drawable/ic_arrow_down_black_36.xml
  app/src/main/res/drawable/ic_back_button_gray_600_45.xml
  app/src/main/res/drawable/ic_back_gray_800_24.xml
  app/src/main/res/drawable/ic_call_gray_500_24.xml
  app/src/main/res/drawable/ic_location_gray_500_24.xml
  app/src/main/res/drawable/ic_people_grey_100_24.xml
  app/src/main/res/drawable/ic_polygon_gray_800_8.xml
  app/src/main/res/drawable/ic_refresh_gray_600_45.xml
  app/src/main/res/drawable/ic_star_yellow_14.xml
  app/src/main/res/drawable/ic_store_gray_500_24.xml
  app/src/main/res/drawable/shape_8dp_bg_gray_700.xml
  app/src/main/res/layout/activity_popular_store.xml
  app/src/main/res/layout/activity_waiting_detail.xml
  app/src/main/res/layout/item_popular_store.xml
  app/src/main/res/menu/menu_waiting_detail_tb.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 💫 feat 💫, ➡️ 민우 ➡️

#12 [feat] 이용예정/완료 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/tabling/data/model/request/RequestDummyDto.kt
  app/src/main/java/org/sopt/tabling/data/model/response/ResponseDummyDto.kt
  app/src/main/java/org/sopt/tabling/data/model/response/ResponseOrdersDto.kt
  app/src/main/java/org/sopt/tabling/domain/model/DummyData.kt
  app/src/main/java/org/sopt/tabling/domain/model/ReservationItem.kt
  app/src/main/java/org/sopt/tabling/presentation/common/ReservationViewModel.kt
  app/src/main/java/org/sopt/tabling/presentation/dummy/DummyActivity.kt
  app/src/main/java/org/sopt/tabling/presentation/dummy/DummyViewModel.kt
  app/src/main/java/org/sopt/tabling/presentation/queue/QueueCancelFragment.kt
  app/src/main/java/org/sopt/tabling/presentation/queue/QueueDetailsActivity.kt
  app/src/main/java/org/sopt/tabling/presentation/queue/QueueReservationFragment.kt
  app/src/main/java/org/sopt/tabling/presentation/queue/ReservationAdapter.kt
  app/src/main/java/org/sopt/tabling/presentation/queue/ReservationDoneViewHolder.kt
  app/src/main/java/org/sopt/tabling/presentation/queue/ReservationViewHolder.kt
  app/src/main/res/drawable/ic_arrow_back_45.xml
  app/src/main/res/drawable/ic_arrow_front_31.xml
  app/src/main/res/drawable/shape_gray_100_line_8_rect.xml
  app/src/main/res/drawable/shape_white_line_8_rect.xml
  app/src/main/res/layout/activity_queue_details.xml
  app/src/main/res/layout/fragment_queue_cancel.xml
  app/src/main/res/layout/fragment_queue_reservation.xml
  app/src/main/res/layout/item_done_reservation.xml
  app/src/main/res/layout/item_reservation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 💫 feat 💫, 🐹 지은 🐹

#14 [feat] 대기 신청 완료 팝업 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/tabling/presentation/dummy/DummyViewModel.kt
  app/src/main/java/org/sopt/tabling/presentation/dummy/MainActivity.kt
  app/src/main/java/org/sopt/tabling/presentation/dummy/WaitingDialog.kt
  app/src/main/res/drawable/ic_exit_24.xml
  app/src/main/res/drawable/ic_info_24.xml
  app/src/main/res/drawable/ic_waiting_16.xml
  app/src/main/res/drawable/shape_gray_000_fill_4.xml
  app/src/main/res/drawable/shape_gray_600_fill_4.xml
  app/src/main/res/drawable/shape_primary_fill_8_rect.xml
  app/src/main/res/drawable/shape_white_fill_6.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_waiting.xml
  app/src/main/res/values/strings.xml
Labels: 💫 feat 💫, 🐹 지은 🐹

#17 [feat] 지역 인기 매장 API 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/tabling/data/ApiFactory.kt
  app/src/main/java/org/sopt/tabling/data/service/PopularStoreService.kt
  app/src/main/java/org/sopt/tabling/presentation/store/PopularStoreActivity.kt
  app/src/main/java/org/sopt/tabling/presentation/store/StoreViewModel.kt
  app/src/main/res/drawable/shape_gray_200_6.xml
  app/src/main/res/layout/activity_popular_store.xml
  app/src/main/res/layout/item_popular_store.xml
  app/src/main/res/values/themes.xml
Labels: 💫 feat 💫, ➡️ 민우 ➡️
